---
title: MangoDocs
description: A client documentation system
baseurl: ''
permalink: "/:title/"
url: https://livingstreets.mangodocs.online
brand:
  image: logo.svg
  text: MangoDocs
  size: 64px
navbar:
  mobile_left: Navigate
  mobile_right: Menu
author:
  name: Simon Barrett
  github: mightymango
authors:
  simon:
    name: Simon Barrett
    github: mightymango
social:
  email: simon@mightymango.ltd
  website: https://mightymango.ltd
  facebook: 
  flickr: 
  dribbble: 
  github: https://github.com/mightymango
  googleplus: 
  instagram: 
  linkedin: 
  pinterest: 
  twitter: https://twitter.com/MightyMangoLtd
  vimeo: 
  youtube: 
twitter_username: mightymangoltd
footer:
  copyright: Made by a <a href="https://simonbarrett.dev/">human</a> somewhere on
    the planet earth.
disqus:
  shortname: 
google_analytics: 
google_maps_api_key: AIzaSyAwdNUqXQvtWSxpBW6ZOe_X5z5irh6el5o
paginate: 10
paginate_path: "/news/:num/"
post_assets: "/assets/posts/"
image_assets: "/assets/img/"
markdown: kramdown
highlighter: rouge
plugins_dir:
- jekyll-feed
- jekyll-seo-tag
- jekyll-gist
- jekyll-avatar
- jekyll-email-protect
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- README.md
sass:
  style: compressed
collections:
  docs:
    output: true
