---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _docs
  label: Docs
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: Data
- type: document
  path: _data/changelog.yml
  label: Changelog
- type: document
  path: _data/navigation_docs.yml
  label: Navigation (Docs)
- type: document
  path: _data/navigation_home.yml
  label: Navigation (Home)
  match: "**/*"
- type: document
  path: _data/navigation_header.yml
  label: Navigation (Header)
  match: "**/*"
- type: document
  path: _data/navigation_footer.yml
  label: Navigation (Footer)
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
